language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t karlfock/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true karlfock/docker-react npm run test